#!/bin/sh
# Generated by kernelinit
qemu-system-x86_64 \
    -nographic \
    -no-reboot \
    -monitor /dev/null \
    -kernel bzImage \
    -initrd kernelinit/my-rootfs.cpio \
    -append 'console=ttyS0 loglevel=7 oops=panic panic=0 pti=off nokaslr quiet' \
    -m 128M \
    -cpu qemu64,+smep \
    -s
